os:
  - windows
  - linux
  - osx
language: node_js
node_js:
  - lts/dubnium
  - '11.10.1'
sudo: false
before_script:
  - npm run bootstrap
script:
  - 'npm run test:ci'
cache:
  directories:
    - node_modules
